---
- elb_target_group:
    aws_access_key: "{{ ACCESS_KEY_ID }}"
    aws_secret_key: "{{ SECRET_ACCESS_KEY }}"
    name: tg-cogknit
    region: ap-south-1
    protocol: http
    port: 80
    vpc_id: "{{ vpc_id }}"
    health_check_path: /
    successful_response_codes: "200,250-260"
    target_type: ip
    state: present
    wait_timeout: 200
    wait: True
  register: tg_out

- set_fact:
    tg_arn: "{{ tg_out.target_group_arn }}"
    tg_name: "{{ tg_out.target_group_name}}"

- debug:
    var: tg_arn

- name: example using security group rule descriptions
  ec2_group:
    name: sg
    description: sg with rule descriptions
    vpc_id: "{{ vpc_id }}"
    region: ap-south-1
    rules:
      - proto: tcp
        ports:
        - 80
        - 8080
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow all traffic
  register: sg

- set_fact:
    sg: "{{ sg.group_id }}"

- elb_application_lb:
    aws_access_key: "{{ ACCESS_KEY_ID }}"
    aws_secret_key: "{{ SECRET_ACCESS_KEY }}"
    region: ap-south-1
    scheme: internet-facing
    name: alb-cogknit
    security_groups:
      - "{{ sg }}"
    subnets:
      - "{{ pb_sub_1 }}"
      - "{{ pb_sub_2 }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ tg_name }}"
    state: present
  register: alb_out
