---
- elb_target_group:
    aws_access_key: AKIAR5JHB4V66RNRV4Y2
    aws_secret_key: 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
    name: tg-cogknit
    region: ap-south-1
    protocol: http
    port: 80
    vpc_id: vpc-864857ee
    health_check_path: /
    successful_response_codes: "200,250-260"
    target_type: ip
    state: present
    wait_timeout: 200
    wait: True
  register: tg_out

- set_fact:
    tg_arn: "{{ tg_out.target_group_arn }}"
    tg_name: "{{ tg_out.target_group_name}}"

- debug:
    var: tg_arn

- elb_application_lb:
    aws_access_key: AKIAR5JHB4V66RNRV4Y2
    aws_secret_key: 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
    region: ap-south-1
    scheme: internet-facing
    name: alb-cogknit

    security_groups:
      - sg-05facd67
      - sg-09043bc00b78e2833
    subnets:
      - subnet-031e2e232002ce27a
      - subnet-0e9f9947d55e3cdea
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ tg_name }}"
    state: present
  register: alb_out
