---
- ecs_cluster:
    name: my-cluster
    state: present
    region: ap-south-1
    aws_access_key: AKIAR5JHB4V6VUQPQSM6
    aws_secret_key: 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

- ecs_service:
    state: present
    name: my-service
    cluster: my-cluster
    task_definition: manish
    desired_count: 1
    aws_access_key: AKIAR5JHB4V6VUQPQSM6
    aws_secret_key: 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
    launch_type: FARGATE
    network_configuration:
      subnets:
      - 
      security_groups:
      - sg-aaaa1111
      - my_security_group
    deployment_configuration:
      minimum_healthy_percent: 75
      maximum_percent: 150
    placement_constraints:
      - type: memberOf
        expression: 'attribute:flavor==test'
    placement_strategy:
      - type: binpack
        field: memory
